### ISSUE TITLE
Ransomwaretracker has been discontinued

### ISSUE THREAD

**Issue by pe3zx** [PaloAltoNetworks/minemeld-node-prototypes#113]
According to [the page](https://ransomwaretracker.abuse.ch/), Ransomware Tracker has been discontinued on Dec 8th, 2019.

Please considering remove the miner.

**Comment by jtschichold** [comment]
Hi @pe3zx,
thank you. I have marked all the feeds as deprecated and redirected them to a non existent URL owned by US.
We won't delete the Miners to avoid breaking existing configs during auto updates.
