### ISSUE TITLE
OpenBL.org is out of service.

### ISSUE THREAD

**Issue by simonsigre** [PaloAltoNetworks/minemeld-node-prototypes#45]
OpenBL.org is no longer maintained (sad day) .
"Sorry to announce but due to time and financial constraints http://OpenBL.org  will stop updating end of April and shutdown end of May." - https://twitter.com/sshblorg?lang=en

So this prototype should be removed,

**Comment by jtschichold** [comment]
Hi @simonsigre,
thanks. The prototype won't be removed to avoid issues with backward compatibility but it has been already marked as Deprected: https://github.com/PaloAltoNetworks/minemeld-node-prototypes/blob/master/prototypes/openbl.yml#L24

Thanks,
luigi
