### ISSUE TITLE
Site going offline `blutmagie.yml` (https://torstatus.blutmagie.de/)

### ISSUE THREAD

**Issue by simonsigre** [PaloAltoNetworks/minemeld-node-prototypes#91]
As per https://torstatus.blutmagie.de;
```Attention: This Tor Network Status site will be discontinued 11/06/2018, olaf.selke@blutmagie.de```

This site will no longer function after 6th November.   Suggest migrating to using the `torproject` exit node list `https://check.torproject.org/cgi-bin/TorBulkExitList.py?ip=1.1.1.1`

**Comment by jtschichold** [comment]
Thanks @simonsigre. Probably the best replacement is the tor exit address list: https://github.com/PaloAltoNetworks/minemeld-node-prototypes/blob/master/prototypes/tor.yml#L9

What do you think?

**Comment by simonsigre** [comment]
Yeah that's probably better, I am actually using both because the fact they have a 'checker' implies that certain exit nodes are blocking traffic to certain places and given its decentralised I can only imagine to build the `https://check.torproject.org/exit-addresses` they are testing them somehow and if someone didn't want to appear on that list (so their node was undetected) they would simply need to block connectivity to whatever was being used as the test.
However, I might have that all wrong :) I am happy to mark this as completed and ill run both side by side and let you know if I see a difference.

**Comment by simonsigre** [comment]
I am seeing a pretty large discrepancy (against https://github.com/PaloAltoNetworks/minemeld-node-prototypes/blob/master/prototypes/tor.yml#L9) however this can be time based.
I will leave it a little longer, but, I think I will certainly be keeping both.

**Comment by simonsigre** [comment]
For whatever reason I am seeing a huge discrepancy still.. happy to close it out though

**Comment by simonsigre** [comment]
@jtschichold I think this discrepancy may be a simple matter of timing etc (bring data in, age out etc) .. I think its fine to mark this as resolved.

**Comment by simonsigre** [comment]
@jtschichold this one is good to mark as resolved

**Comment by jtschichold** [comment]
Marked blutmagie as deperecated
