### ISSUE TITLE
Service Removed `feodotracker.domainblocklist`

### ISSUE THREAD

**Issue by simonsigre** [PaloAltoNetworks/minemeld-node-prototypes#95]
The prototype `feodotracker.domainblocklist` no longer function as the service `https://feodotracker.abuse.ch/blocklist/?download=domainblocklist` no longer seems to offer a `domain` service.

Prototype just imports garbage now;
```
<p>
<p>&copy;
<p><a
<p>As
<p>By
<p>Dridex
<p>Feodo
<p>I
<p>If
<p>In
<p>The
<script
<section
<span
<title>Feodo
<ul
<ul>
```

**Comment by jtschichold** [comment]
This was addresses with #96 

Thanks!
